Repository Azure/data-product-batch, pull requests merged in 2021-11, with the labels that each got.

#100 Updated Codeowners
  .github/CODEOWNERS
Labels: enhancement, committed

#99 Make Cosmos DB & SQL Pool Deployment Optional
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
  docs/EnterpriseScaleAnalytics-Prerequisites.md
  docs/reference/portal.dataProduct.json
  infra/main.bicep
  infra/main.json
  infra/modules/services/synapse.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: enhancement, committed

#102 updated params in docs for ADO and GitHub
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
Labels: documentation

#103 Azure CLI Action Bugfix
  .github/workflows/dataProductDeployment.yml
Labels: bug, committed

#105 Update portal.dataProduct.json
  docs/reference/portal.dataProduct.json
Labels: documentation
