Repository Azure/data-product-batch, pull requests merged in 2022-01, with the labels that each got.

#112 Improving Region Availability
  .github/linters/.arm-ttk.psd1
  docs/DataManagementAnalytics-Prerequisites.md
  docs/reference/portal.dataProduct.json
  infra/main.json
  infra/modules/services/datafactory.bicep
  infra/modules/services/mariadb.bicep
  infra/modules/services/synapse.bicep
Labels: enhancement, committed

#113 Rename data management zone
  README.md
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/DataManagementAnalytics-Prerequisites.md
  docs/DataManagementAnalytics-ServicePrincipal.md
  docs/reference/portal.dataProduct.json
Labels: documentation

#114 Fix Portal UI Bug
  docs/reference/portal.dataProduct.json
Labels: bug

#115 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
